#
# Copyright (c) 2012 by Pawel Tomulik
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE


Import('env')

from SConsGnuVariables import GnuDirVariables

GnuDirVariables.AddToSConsOptions( only = ['prefix', 'exec_prefix'] )
gnuvars = GnuDirVariables.AsSConsVariables( exclude = ['prefix', 'exec_prefix'] )
gnuvars.Update(env, ARGUMENTS)
env.Append( prefix = GetOption('prefix') )
env.Append( exec_prefix = GetOption('exec_prefix') )
env.Append( package = 'mypkg' )

if not GetOption('help'):
   print 'Some of the GNU dir variables:'
   print '  bindir=%s' % env.subst('${bindir}')
   print '  sbindir=%s' % env.subst('${sbindir}')
   print '  sysconfdir=%s' % env.subst('${sysconfdir}')
   print '  pkglibdir=%s' % env.subst('${pkglibdir}')
   print '  man2dir=%s' % env.subst('${man2dir}')
   print '  man2ext=%s' % env.subst('${man2ext}')
