#
# Copyright (c) 2012 by Pawel Tomulik
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE


Import('env')

from SConsGnuVariables import GnuDirVariables
gnuvars = GnuDirVariables.AsSConsVariables(only=['prefix','exec_prefix','bindir'])
gnuvars.Update(env, ARGUMENTS)
Help(gnuvars.GenerateHelpText(env))

if not GetOption('help'):
    print ""
    print "There are three command line variables (GNU dir variables)"
    print "currently defined as:"
    print "=========================================================="
    print "     prefix=%s" % repr(env['prefix'])
    print "     exec_prefix=%s" % repr(env['exec_prefix'])
    print "     bindir=%s" % repr(env['bindir'])
    print "=========================================================="
    print ""
    print "After substitution (interpolation) they have values:"
    print "=========================================================="
    print "     prefix=%s" % repr(env.subst('${prefix}'))
    print "     exec_prefix=%s" % repr(env.subst('${exec_prefix}'))
    print "     bindir=%s" % repr(env.subst('${bindir}'))
    print "=========================================================="
